### ISSUE TITLE
Field upgrades / repairs

### ISSUE THREAD

**Issue by lramati** [tyrope/fencing#17]
Allow players to slime string fences without first destroying them. 
Goes hand in hand with Issue #16, allowing a method to repair cut fences without first digging them up and having a workbench handy

**Comment by tyrope** [comment]
- [x] Right click on string fence with slime ball uses slime ball to upgrade.
- [x] Right click cut fence (See issue 16 TODO list) with material to update. (Probably won't work on electric fences).

Marked as 'future' for now. ETA: 0.4

**Comment by tyrope** [comment]
https://github.com/tyrope/fencing/commit/dd6f183afd1bc699495c1f91670124043398393b adds the ability to repair cut fences, except for silly string and electric fences.
