### ISSUE TITLE
Crash on render.

### ISSUE THREAD

**Issue by tyrope** [tyrope/fencing#28]
I can't for the life of me figure out how to fix it...

Cause: [FenceBlockItem.registerIcons](https://github.com/tyrope/fencing/blob/master/src/main/java/nl/tyrope/fencing/items/FenceBlockItem.java#L22-L30) is never called.
Possible fix: Something with [FenceBlock.registerBlockIcons](https://github.com/tyrope/fencing/blob/master/src/main/java/nl/tyrope/fencing/blocks/FenceBlock.java#L292-L300)?

**Comment by buglord** [comment]
as we chatted about, blocks are being registered in init, move what should be moved over to preInit.
I haven't quite gotten into the structure of minecraft modding and such, so I'll leave it up to you to move things over with the prefered structuring.

**Comment by tyrope** [comment]
Fixed in 15cd3a4bd77919a84c36a52a942111475ea59f39
