### ISSUE TITLE
IC2 electric fence infinite battery bug

### ISSUE THREAD

**Issue by buglord** [tyrope/fencing#30]
two fences placed next to each other resulting in an infinite battery;
cause: energy offered is max(0, buffer - voltage), and all energy is accepted and overflows into the other fence.
quick fix: change energy offered to min(buffer,voltage), not recommended in long term because it bounces energy around and is inefficient with server resources.

**Comment by buglord** [comment]
sorry, button says close, totally needs to say close issue, because I thought it was gonna close the input window.

**Comment by tyrope** [comment]
The temporary 'fix' in PR31 doesn't actually fix it. MFSU-Tin Fence-MFSU causes the source MFSU to stay full while the other charges.

**Comment by tyrope** [comment]
We're switching over to the Universal Electricity API in Fencing0.6 / Minecraft1.8. Which will more than likely require a rewrite. Closing this prematurely.
